version: '3.7'

services:
    liferay:
        image: liferay/portal:7.3.0-ga1
        environment:
            LIFERAY_LOCALES_PERIOD_ENABLED: es_ES,ca_ES,en_US
            LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
            LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: lportal
            LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://liferay-db/lportal?characterEncoding=UTF-8&&dontTrackOpenResources=true&&holdResultsOpenOverStatementClose=true&&serverTimezone=GMT&&useFastDateParsing=false&&useUnicode=true
            LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: lportal
            LIFERAY_LAYOUT_PERIOD_SHOW_PERIOD_PORTLET_PERIOD_ACCESS_PERIOD_DENIED: 'false'
            LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_AUTH_PERIOD_TYPE: screenName
            LIFERAY_SESSION_PERIOD_STORE_PERIOD_PASSWORD: 'true'
        ports:
            - 8086:8080
            - 8000:8000
        depends_on:
          - liferay-db
        volumes:
            - type: bind
              source: ./liferay-volume
              target: /opt/liferay/data
            - type: bind
              source: ./liferay
              target: /mnt/liferay

    keycloak:
        image: jboss/keycloak:8.0.1
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            DB_USER: keycloak
            DB_PASSWORD: keycloak
            DB_VENDOR: mysql
            DB_ADDR: keycloak-db
            DB_DATABASE: keycloak
            KEYCLOAK_IMPORT: /tmp/in2-realm-export.json
        ports:
            - 8080:8080
        depends_on:
          - keycloak-db
        volumes:
            - type: bind
              source: ./keycloak/in2-realm-export.json
              target: /tmp/in2-realm-export.json
            - type: bind
              source: ./keycloak/configs/profile.properties
              target: /opt/jboss/keycloak/standalone/configuration/profile.properties

    liferay-db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: lportal
            MYSQL_USER: lportal
            MYSQL_PASSWORD: lportal
        ports:
            - 3319:3306
        volumes:
            - type: bind
              source: ./liferay-db-volume
              target: /var/lib/mysql

    keycloak-db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: keycloak
        ports:
            - 3314:3306
        volumes:
            - type: bind
              source: ./keycloak-db-volume
              target: /var/lib/mysql

    alfresco:
        image: alfresco/alfresco-content-repository-community:6.2.0-ga
        #mem_limit: 1500m
        environment:
            JAVA_OPTS: "
                    -Ddb.driver=org.postgresql.Driver
                    -Ddb.username=alfresco
                    -Ddb.password=alfresco
                    -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                    -Dsolr.host=solr6
                    -Dsolr.port=8983
                    -Dsolr.secureComms=none
                    -Dsolr.base.url=/solr
                    -Dindex.subsystem.name=solr6
                    -Dshare.host=localhost
                    -Dshare.port=80
                    -Dalfresco.host=localhost
                    -Dalfresco.port=80
                    -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                    -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                    -Ddeployment.method=DOCKER_COMPOSE

                    -Dlocal.transform.service.enabled=true
                    -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                    -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                    -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                    -DlocalTransform.tika.url=http://tika:8090/
                    -DlocalTransform.misc.url=http://transform-misc:8090/

                    -Dlegacy.transform.service.enabled=true
                    -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                    -Djodconverter.url=http://libreoffice:8090/
                    -Dimg.url=http://imagemagick:8090/
                    -Dtika.url=http://tika:8090/
                    -Dtransform.misc.url=http://transform-misc:8090/

                    -Dcsrf.filter.enabled=false
                    -Xms1500m -Xmx1500m

                    -Dmail.host=smtp
                    -Dmail.port=5025
                    -Dmail.username=
                    -Dmail.password=
                    -Dmail.protocol=smtp
                    -Dmail.smtps.starttls.enable=false
                    -Dmail.smtps.auth=false
                    -Dmail.testmessage.send=true
                    -Dmail.testmessage.to=foo@bar.es
                    -Dmail.testmessage.subject=\"Test mail Alfresco 6.2\"
                    -Dmail.testmessage.text=\"Test mail alfresco 6.2 is working!\"

                    -Dalfresco.restApi.basicAuthScheme=true
                    -Dauthentication.protection.enabled=false
                    -Daudit.enabled=false
                    -Dsample.site.disabled=true
                    -Dheartbeat.enabled=false
                    -Dsystem.serverMode=TEST
                    -Dreplication.enabled=false
                    -Daudit.enabled=false
                    -Dcifs.enabled=false
                    -Dftp.enabled=false
                    -Dtransferservice.receiver.enabled=false
                    -Daudit.alfresco-access.enabled=false
                    -Daudit.filter.alfresco-access.default.enabled=false

                    -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
                    -Didentity-service.authentication.enabled=true
                    -Didentity-service.enable-basic-auth=true
                    -Didentity-service.authentication.defaultAdministratorUserNames=admin
                    -Didentity-service.authentication.validation.failure.silent=false
                    -Didentity-service.auth-server-url=http://keycloak:8080/auth
                    -Didentity-service.authentication.allowGuestLogin=false
                    -Didentity-service.realm=in2
                    -Didentity-service.resource=alfresco
                    -Didentity-service.public-client=false
                    -Didentity-service.ssl-required=none
                    -Didentity-service.credentials.secret=c286c6ec-d956-41a8-bb7e-cff69880846e

                    "
        depends_on:
          - keycloak

    alfresco-pdf-renderer:
        image: alfresco/alfresco-pdf-renderer:2.1.0
        #mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
        ports:
            - 8090:8090

    imagemagick:
        image: alfresco/alfresco-imagemagick:2.1.0
        #mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
        ports:
            - 8091:8090

    libreoffice:
        image: alfresco/alfresco-libreoffice:2.1.0
        #mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
        ports:
            - 8092:8090

    tika:
        image: alfresco/alfresco-tika:2.1.0
        #mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
        ports:
            - 8093:8090

    transform-misc:
        image: alfresco/alfresco-transform-misc:2.1.0
        #mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
        ports:
            - 8094:8090

    share:
        image: alfresco/alfresco-share:6.2.0
        #mem_limit: 1g
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -Xms500m
                -Xmx500m
                -Dalfresco.host=localhost
                -Dalfresco.port=80
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
        ports:
            - 8084:8080

    postgres:
        image: postgres:11.4
        #mem_limit: 512m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:1.4.0
        #mem_limit: 2g
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
            #HTTP by default
            - ALFRESCO_SECURE_COMMS=none
            - "SOLR_JAVA_MEM=-Xms2g -Xmx2g"
        ports:
            - 8083:8983 #Browser port

    activemq:
        image: alfresco/alfresco-activemq:5.15.8
        #mem_limit: 1g
        ports:
          - 8161:8161 # Web Console
          - 5672:5672 # AMQP
          - 61616:61616 # OpenWire
          - 61613:61613 # STOMP

    content-app:
        image: alfresco/alfresco-content-app:master
        depends_on:
            - alfresco
            - share
        environment:
            SERVER_PATH: /app
            APP_CONFIG_AUTH_TYPE: OAUTH
            APP_CONFIG_OAUTH2_HOST: http://keycloak:8080/auth/realms/in2
            APP_CONFIG_OAUTH2_CLIENTID: app
            APP_CONFIG_OAUTH2_REDIRECT_LOGIN: "/app"
            APP_CONFIG_OAUTH2_REDIRECT_LOGOUT: "/app/logout"

    smtp:
        image: gessnerfl/fake-smtp-server
        environment:
            JAVA_OPTS: "-Duser.timezone=CET"
            SERVER_SERVLET_CONTEXT_PATH: "/mail"

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx-config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
        depends_on:
            - alfresco
            - share
        ports:
            - 80:80